table customers
	lineageTag: 1f2c60a7-8ba9-46eb-a7bc-e6f1c0042878

	column customer_id
		dataType: string
		lineageTag: 9e37c43c-7922-4ef3-b5b4-5b0fc4df3fe9
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: 7b68f3af-b28a-4bd8-819d-d8dcbf6175eb
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 2d8ebc7e-7117-4512-95a9-4ae5f6a79366
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: bedb53d2-b030-4dd9-952f-fcde83591600
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: bbd357df-d918-480f-96a6-8cdd509f4970
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 11a940cf-03c5-4fdf-8414-6a01fbb2999e
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column occupation_segment
		dataType: string
		lineageTag: a5931c85-c6e3-405f-8e05-41816645e8f3
		summarizeBy: none
		sourceColumn: occupation_segment

		annotation SummarizationSetBy = Automatic

	column annual_income
		dataType: int64
		formatString: 0
		lineageTag: 16c4f372-99f1-48b4-af7b-963285c646c1
		summarizeBy: sum
		sourceColumn: annual_income

		annotation SummarizationSetBy = Automatic

	column risk_band
		dataType: string
		lineageTag: 7931d3d1-789c-40ea-a066-697507a7a4f0
		summarizeBy: none
		sourceColumn: risk_band

		annotation SummarizationSetBy = Automatic

	column join_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e587eef3-6a65-45bc-a61f-0302f806e05c
		summarizeBy: none
		sourceColumn: join_date
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column home_branch_id
		dataType: string
		lineageTag: c482a671-3ae9-4483-a2ac-cb005b6d143e
		summarizeBy: none
		sourceColumn: home_branch_id

		annotation SummarizationSetBy = Automatic

	column digital_engagement_score
		dataType: double
		lineageTag: 13253627-335b-4ba5-95b1-a5f50cdadada
		summarizeBy: sum
		sourceColumn: digital_engagement_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_churned
		dataType: int64
		formatString: 0
		lineageTag: fa9f344f-745e-41fa-9158-70c29ca23e99
		summarizeBy: sum
		sourceColumn: is_churned

		annotation SummarizationSetBy = Automatic

	measure 'Total Customers' = DISTINCTCOUNT(customers[customer_id])
		formatString: #,0
		displayFolder: Customers

	measure 'Churned Customers' = CALCULATE([Total Customers], customers[is_churned] = 1)
		formatString: #,0
		displayFolder: Customers

	measure 'Customer Churn Rate' = DIVIDE([Churned Customers], [Total Customers])
		formatString: 0.0%
		displayFolder: Customers

	measure 'Average Digital Engagement' = AVERAGE(customers[digital_engagement_score])
		formatString: 0.00
		displayFolder: Customers

	partition customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\janak\Downloads\FinTrust-Banking-Intelligence-main\FinTrust-Banking-Intelligence-main\data\raw\customers.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"full_name", type text}, {"age", Int64.Type}, {"gender", type text}, {"city", type text}, {"state", type text}, {"occupation_segment", type text}, {"annual_income", Int64.Type}, {"risk_band", type text}, {"join_date", type date}, {"home_branch_id", type text}, {"digital_engagement_score", type number}, {"is_churned", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

