table interactions
	lineageTag: cd849135-4436-4568-9f1d-8f2c1b64aab6

	column interaction_id
		dataType: string
		lineageTag: b315e2cc-9925-48f8-8a52-d05f9ecec692
		summarizeBy: none
		sourceColumn: interaction_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: b35636cb-b796-45d0-bed3-11f4bea66ac4
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column interaction_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b9c7489-ce89-48e1-88ba-bf0e0a58f084
		summarizeBy: none
		sourceColumn: interaction_date
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column channel
		dataType: string
		lineageTag: bd3525d5-5dd6-4f19-ac7e-99d86871a16e
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column reason
		dataType: string
		lineageTag: 4b85f238-d67d-4b75-a2ff-5556fe4611f0
		summarizeBy: none
		sourceColumn: reason

		annotation SummarizationSetBy = Automatic

	column resolution_hours
		dataType: double
		lineageTag: a53e59c2-a63e-4419-83f1-d91a6ae14989
		summarizeBy: sum
		sourceColumn: resolution_hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column satisfaction_score
		dataType: int64
		formatString: 0
		lineageTag: 9bc91d01-1905-43fe-a075-24335344f97f
		summarizeBy: sum
		sourceColumn: satisfaction_score

		annotation SummarizationSetBy = Automatic

	measure 'Customer Interactions' = COUNTROWS(interactions)
		formatString: #,0
		displayFolder: Customer Experience

	measure 'Average Resolution Hours' = AVERAGE(interactions[resolution_hours])
		formatString: 0.0
		displayFolder: Customer Experience

	measure 'Average Satisfaction Score' = AVERAGE(interactions[satisfaction_score])
		formatString: 0.00
		displayFolder: Customer Experience

	measure 'Complaint Rate' = DIVIDE(CALCULATE([Customer Interactions], interactions[reason] = "Complaint"), [Customer Interactions])
		formatString: 0.0%
		displayFolder: Customer Experience

	partition interactions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\janak\Downloads\FinTrust-Banking-Intelligence-main\FinTrust-Banking-Intelligence-main\data\raw\interactions.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"interaction_id", type text}, {"customer_id", type text}, {"interaction_date", type date}, {"channel", type text}, {"reason", type text}, {"resolution_hours", type number}, {"satisfaction_score", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

