name: fintrust
version: '1.0.0'
config-version: 2
profile: fintrust
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]
models:
  fintrust:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

